Add possibility to add a contact person from a company as deal lead
teamleadercrm/api pull request #128
Opened 2018-04-20 08:32 UTC by jenssegers

Currently it is impossible to add an additional contact person from a company as deal lead.

The PR allows people to add either or both `contact_id` and `company_id` as a lead. The `lead` filter behaves similar as before and will search on both of these fields for convenience.

2018-04-20 08:46 UTC, WouterSioen reviewed
Looking good, but this is a BC breaking change, so not sure if we can easily do this.

Is this endpoint already used?

Otherwise we might want to think about a migration path for this.

2018-04-20 10:30 UTC, stivni commented
Why don’t stick to the same principle & terminology as in the reads? 

Lead
- Customer
  - type: contant or company
  - id
- for_ attention_of: a contact_id

?

2018-04-20 10:32 UTC, stivni requested changes
This doesn’t follow what we decided during the last discussion we had about this...

2018-04-20 10:34 UTC, jenssegers commented
@stivni I know, we had a discussion about this. For attention of does not make sense on deal level. Only on invoice/quotation. In the deal domain, this is your contact person.

2018-04-20 10:45 UTC, mrtus reviewed
This will break some things on the IT side of things...

Also if company & contact are used both? Is the contact meant to be the representative for the company? (We already talked about this before...)

2018-04-23 11:39 UTC, jenssegers commented
Closing in favour of https://github.com/teamleadercrm/api/pull/129

2018-04-23 11:39 UTC, closed without merging