Add optional opted_in_for_mailings to companies.add
teamleadercrm/api pull request #168
Opened 2018-06-08 14:14 UTC by rathesDot

### Added

- optional `opted_in_for_mailings` for `companies.add`

2018-06-11 08:07 UTC, JordyDeGroeve approved these changes

2018-06-11 08:09 UTC, WouterSioen approved these changes

2018-06-11 14:32 UTC, dietrichm approved these changes

2018-06-11 14:33 UTC, dietrichm commented
Let's merge it once the implementation is deployed.

2018-06-11 15:38 UTC, jenssegers commented
Not the biggest fan of the property name, but also don't really have an alternative.

2018-06-12 12:10 UTC, WouterSioen requested changes
Blocking since we'll probably structure this differently

2018-06-14 09:38 UTC, closed without merging