More information about departments
teamleadercrm/api pull request #240
Opened 2018-11-09 10:47 UTC by jenssegers

Reverts the revert on https://github.com/teamleadercrm/api/pull/110

2018-11-09 10:49 UTC, luisaterrabrito approved these changes

2018-11-09 10:54 UTC, WouterSioen requested changes
Agreeing on the implementation but blocking to avoid the same thing to happen

2018-11-09 10:54 UTC, dietrichm approved these changes

2018-11-09 11:08 UTC, dcsg approved these changes

2018-11-13 14:05 UTC, WouterSioen approved these changes

2018-11-13 14:06 UTC, merged