Add withholding taxes to invoices info
teamleadercrm/api pull request #242
Opened 2018-11-13 14:30 UTC by luisabritotl

2018-11-13 14:49 UTC, dcsg requested changes

2018-11-13 14:49 UTC, dcsg commented on apiary.apib
> +                            + withholding_tax (object)
Q/B: this should be nullable, right?

2018-11-13 14:49 UTC, dcsg commented on apiary.apib
> +                + withholding_taxes (array)
Will be weird for the countries where it does not apply to have this in the response.

2018-11-13 14:55 UTC, dcsg submitted a review, later dismissed

2018-11-14 11:07 UTC, luisabritotl commented
Actually, implementing this, I noticed the vat rate is presented as zero not null. The withholding tax might not apply to an invoice in case the country is not Italy, but we cannot check that for an item. So should the withholding tax return the tax as zero either way?
@dcsg @jenssegers @steftrenson @jdrieghe

2018-11-14 12:55 UTC, dcsg commented
IMO if the user didn't set the withholding tax than it should not be zero and the object should not exist or is null.

2018-11-28 11:53 UTC, tiagobastos approved these changes

2018-11-29 13:37 UTC, steftrenson approved these changes

2018-11-29 13:39 UTC, dcsg approved these changes

2018-11-29 14:47 UTC, merged