Add proposal for the users.list filter on term
teamleadercrm/api pull request #272
Opened 2019-01-21 07:42 UTC by WouterSioen

It can filter on username, "real name" and email address (we can add more later if this doesn't cover it all, but this seems like a sensible start to me)

2019-01-21 08:42 UTC, marcwestermann commented
Hey Wouter, thanks for picking this up! The name (first name and last name) is the most interesting filter for us. We are trying to filter the users on an API level to select them as attendees on the new calendar. Maybe, function (position) would also be nice to have, but not required.
![image](https://user-images.githubusercontent.com/15048245/51462354-aa230b00-1d60-11e9-9122-b8c39dd3df11.png)
@duivvv , what do you think? :)

2019-01-21 09:01 UTC, duivvv commented
I think function is nice to have but not essential. I think the combination company / function makes sense in the context of a contact (> 'ceo madewithlove' for example)

2019-01-21 14:46 UTC, dietrichm requested changes

2019-01-21 14:46 UTC, dietrichm commented on src/01-general/users.apib
> +            + term: `John` (string, optional) - Filters on username, real name and email address
B: there is no notion of "real name" in the return data for users. The first and last name is returned as a result from splitting on the first space.

```suggestion
            + term: `John` (string, optional) - Filters on username, first_name, last_name and email
```

Also the username still needs to be added to the user info.

2019-01-21 14:51 UTC, dietrichm submitted a review, later dismissed
PP: username still should be added to the return data.

2019-01-21 14:52 UTC, mrtus submitted a review, later dismissed

2019-01-21 14:52 UTC, mrtus commented on apiary.apib
> +            + term: `John` (string, optional) - Filters on username, first_name, last_name and email
Q: Should we leave out username for now? I don't think it has any use for now.

2019-01-21 15:04 UTC, dietrichm approved these changes

2019-01-21 15:09 UTC, JordyDeGroeve approved these changes

2019-01-21 15:12 UTC, mrtus approved these changes

2019-01-22 10:06 UTC, marcwestermann approved these changes

2019-01-22 11:12 UTC, tiagobastos approved these changes

2019-01-28 14:43 UTC, jenssegers approved these changes

2019-01-28 15:34 UTC, merged