PRO-1380 Add billing method info to milestones.list
teamleadercrm/api pull request #287
Opened 2019-02-05 16:11 UTC by joaoinacio

Implementation PR: https://github.com/teamleadercrm/core/pull/7956
E2E Tests: https://github.com/teamleadercrm/api-tests/pull/480

Updated to reflect naming decided for milestone invoice-ability info:
- changed from `billing_method` to `invoicing method` and include `non_invoiceable`:
https://github.com/teamleadercrm/core/pull/8264
- E2E Tests: https://github.com/teamleadercrm/api-tests/pull/514

JIRA: https://teamleader.atlassian.net/browse/PRO-1462

2019-02-06 09:42 UTC, ketlane approved these changes

2019-02-06 13:42 UTC, ketlane requested changes

2019-02-06 13:42 UTC, ketlane commented on apiary.apib
> +                            + price (Money)
B: We should remove the price here. The price will be exposed under the "profit" information.

2019-02-07 08:27 UTC, ketlane submitted a review, later dismissed

2019-02-07 13:24 UTC, ketlane submitted a review, later dismissed

2019-02-07 15:59 UTC, ArnaudWeyts submitted a review, later dismissed

2019-02-13 09:34 UTC, adognameddog submitted a review, later dismissed

2019-02-18 09:07 UTC, dcsg submitted a review, later dismissed

2019-02-19 08:34 UTC, ArnaudWeyts approved these changes

2019-02-19 08:40 UTC, ketlane approved these changes

2019-02-20 08:33 UTC, adognameddog approved these changes

2019-02-20 08:43 UTC, adognameddog commented
We'll merge this when the implementation and the e2e tests are merged first.

2019-02-21 11:01 UTC, merged