PRO-1462: add invoiceable flag
teamleadercrm/api pull request #291
Opened 2019-02-12 16:03 UTC by ketlane

### Ticket
Link to ticket: https://teamleader.atlassian.net/browse/PRO-1451

In the new project items list, we will need to visually mark uninvoiceable milestones. In order to do this, we will need to expose this information in the API.

2019-02-12 16:18 UTC, jenssegers commented
What does setting a milestone to non-invoiceable exactly do? Is that the same as setting the milestone to fixed-price of 0?

2019-02-12 16:40 UTC, ketlane commented
When invoicing a milestone, you can invoice according to time spent, or according to budget. If you choose "according to time spent", you can still create an invoice for fixed price milestones with 0 budget.

But if you set the "Invoiceable" flag to "No", you can't create an invoice for that milestone.

2019-02-13 10:09 UTC, adognameddog approved these changes

2019-02-13 10:24 UTC, Kemosabert approved these changes

2019-02-13 12:49 UTC, WouterSioen approved these changes

2019-02-13 16:55 UTC, jenssegers requested changes
Sorry for blocking, but I think we're missing out on a different concept here. Briefly checked with @bbouwmeister and seems that we might need to give this some more thought?

2019-02-18 14:34 UTC, adognameddog commented
This can be closed since we agreed on another way of denoting a milestone's billing method.

2019-02-18 14:34 UTC, closed without merging

2019-02-19 08:42 UTC, ketlane commented
See this PR in order to understand how to discover if a milestone is invoiceable or not: https://github.com/teamleadercrm/api/pull/287