workOrders.draft endpoint: MVP
teamleadercrm/api pull request #296
Opened 2019-02-14 14:25 UTC by WouterSioen

Part of https://github.com/teamleadercrm/api/pull/290

2019-02-14 15:10 UTC, JordyDeGroeve submitted a review, later dismissed

2019-02-15 15:21 UTC, tiagobastos submitted a review, later dismissed

2019-02-19 09:36 UTC, dietrichm requested changes

2019-02-19 09:36 UTC, dietrichm commented on src/apiary.apib
> + :[Work Orders](./01-general/work-orders.apib)
B: space at the start of the line (causing weird issues in the compiled file).

2019-02-19 09:36 UTC, dietrichm commented on src/01-general/work-orders.apib
> + ### workOrders.draft [POST /workOrders.draft]
B: spaces at the start of all lines (causing weird issues in the compiled file). The request is not recognized as such.

2019-02-19 10:15 UTC, dietrichm submitted a review, later dismissed

2019-02-19 10:15 UTC, dietrichm commented
✅ Checked

2019-02-19 10:42 UTC, dcsg submitted a review, later dismissed

2019-02-19 14:52 UTC, JorenSaey submitted a review, later dismissed

2019-02-19 15:10 UTC, tiagobastos submitted a review, later dismissed

2019-02-19 16:10 UTC, dietrichm reviewed
Q: just now I'm seeing `starts_at` is not included yet? This is a required property in the proposal denoting the datetime the work is going to be or was carried out.

2019-02-19 16:24 UTC, WouterSioen commented
Will add it tomorrow

2019-02-20 07:12 UTC, WouterSioen commented
Added the missing `starts_at` field (which was not in the main api proposal at the time I made this one)

2019-02-20 09:34 UTC, JordyDeGroeve approved these changes

2019-02-20 10:20 UTC, dietrichm approved these changes

2019-02-20 10:25 UTC, tiagobastos approved these changes

2019-02-21 08:35 UTC, jenssegers approved these changes

2019-02-22 07:53 UTC, merged