Core 1817 workorder draft location
teamleadercrm/api pull request #314
Opened 2019-02-25 16:14 UTC by JordyDeGroeve

Changed the folder structure to reflect the grouping better.

+ added the location to the .draft endpoint for workorders.

## Manual Check
run 
```
make all && make preview && open apiary.html
```
Check if the `location` is added to **workOrders.draft** 
and that the `time-tracking` group is still loaded correctly.

2019-02-25 16:28 UTC, tiagobastos approved these changes
✅ The location (with Address object) is added to the `workorders.draft` endpoint and the time-tracking group is still loaded.

2019-02-25 17:25 UTC, WouterSioen approved these changes

2019-02-26 12:29 UTC, dietrichm requested changes

2019-02-26 12:29 UTC, dietrichm commented on src/09-workorders/work-orders.apib
> +       + location (Address)
B:
```suggestion
       + location (Address, optional)
```

2019-02-26 12:32 UTC, dietrichm approved these changes

2019-02-26 12:39 UTC, WouterSioen requested changes

2019-02-26 12:39 UTC, WouterSioen commented on apiary.apib
> +       + location (Address)
B: this still needs to be build
```suggestion
       + location (Address, optional)
```

2019-02-26 12:51 UTC, JordyDeGroeve commented on apiary.apib
> +       + location (Address)
🤦‍♂️

2019-02-26 13:01 UTC, dietrichm submitted a review, later dismissed
Voilá 💁‍♂️

2019-02-26 13:02 UTC, WouterSioen submitted a review, later dismissed

2019-02-26 13:25 UTC, jenssegers submitted a review, later dismissed

2019-02-26 15:10 UTC, dietrichm commented
🚨 Conflicts

2019-02-27 07:38 UTC, WouterSioen commented
Rebased to fix the conflicts, to be able to work further on this.

2019-02-27 07:44 UTC, WouterSioen commented
✅ looks good

2019-02-27 11:25 UTC, tiagobastos approved these changes

2019-02-27 16:21 UTC, WouterSioen approved these changes
Reviews got dropped by changing the base branch. Still approving

2019-02-27 16:28 UTC, dietrichm approved these changes

2019-03-01 08:17 UTC, merged