Added the products.info end point documentation
teamleadercrm/api pull request #328
Opened 2019-03-07 10:42 UTC by EOSullivanBerlin

2019-03-07 13:06 UTC, luisabritotl commented
Linting problems and you need to do make build to generate the apib file. Are we not going to refer to the current approach and explain the breaking changes?

2019-03-07 14:06 UTC, dcsg requested changes
B: You need to build it :)

2019-03-07 14:06 UTC, dcsg commented on src/06-products/products.apib
> +            + `purchase_price`: (Money nullable)
```suggestion
            + purchase_price (Money, nullable)
```

2019-03-07 15:54 UTC, EOSullivanBerlin commented
I will build it now.

2019-03-07 15:56 UTC, EOSullivanBerlin commented
@luisabritotl I don't know what I need to do to explain the breaking changes. Is there an example of that somewhere?

2019-03-08 08:27 UTC, steftrenson reviewed
Can you change the base branch to the 2019-03-13 branch? And at selling_price as well please.

2019-03-08 08:27 UTC, steftrenson commented on apiary.apib
> +            + `purchase_price`: (Money nullable)
Looks like this wasn't build properly, it differs from products.apib

2019-03-08 15:03 UTC, EOSullivanBerlin commented
This now is a pretty unreadable PR. The changing of the branch base made it pretty confusing. Should I start over?

2019-03-08 15:04 UTC, dcsg commented
Yes, please 😅

2019-03-11 07:55 UTC, closed without merging