Document products info changes
teamleadercrm/api pull request #332
Opened 2019-03-12 10:56 UTC by steftrenson

2019-03-12 10:59 UTC, dcsg requested changes

2019-03-12 10:59 UTC, dcsg commented on apiary.apib
> + + Response 201 (application/json;charset=utf-8)
B: this should be `200`, right?

2019-03-12 11:59 UTC, dcsg approved these changes

2019-03-12 12:51 UTC, lowiebenoot approved these changes

2019-03-12 14:09 UTC, Yarn-e approved these changes

2019-03-12 14:52 UTC, jenssegers commented
@steftrenson Can we have some context in the PR description?

2019-03-12 14:52 UTC, jenssegers approved these changes

2019-03-13 14:42 UTC, EOSullivanBerlin approved these changes

2019-03-28 08:46 UTC, stivni approved these changes

2019-03-28 08:47 UTC, stivni approved these changes

2019-03-28 08:52 UTC, dcsg approved these changes

2019-03-28 08:52 UTC, Yarn-e approved these changes

2019-03-28 08:53 UTC, lowiebenoot approved these changes

2019-03-28 08:56 UTC, luisaterrabrito approved these changes

2019-03-28 10:47 UTC, merged