Return name of layout in the templates.list endpoint
teamleadercrm/api pull request #418
Opened 2019-05-29 11:08 UTC by WouterSioen

This is necessary to visual display templates.

2019-05-29 11:20 UTC, JordyDeGroeve requested changes

2019-05-29 11:20 UTC, JordyDeGroeve commented on src/01-general/document-templates.apib
> +                + name: `new logo` (string)
B: this should be a nullable string. We don't have a name for the default variations. We should return null in this case

2019-05-29 11:26 UTC, JordyDeGroeve approved these changes

2019-05-29 11:27 UTC, JordyDeGroeve commented
Q: should we add a comment in which case that we return `null`? Or is this not needed?

2019-05-29 11:28 UTC, WouterSioen commented
I don't feel like that's necessary?

2019-05-29 12:27 UTC, jdrieghe approved these changes

2019-05-29 13:03 UTC, jenssegers approved these changes

2019-05-29 13:07 UTC, rathesDot approved these changes

2019-05-29 20:14 UTC, stivni approved these changes

2019-05-30 12:17 UTC, tiagobastos approved these changes

2019-05-31 07:17 UTC, merged