[CAL-1391] Return deal_id and milestone_id from tasks.info and tasks.list
teamleadercrm/api pull request #419
Opened 2019-05-29 15:55 UTC by r1dotl

TICKET: https://teamleader.atlassian.net/browse/CAL-1391

Allow the tasks.list and tasks.info to return the milestone_id and deal_id.

If the milestone_id/deal_id don't exist it will return null, but the attribute will be always returned.

2019-05-29 16:02 UTC, psrpinto requested changes

2019-05-29 16:02 UTC, regularjack commented on src/08-tasks/tasks.apib
> +                + milestone_id: `6fac0bf0-e803-424e-af67-76863a3d7d16` (string, nullable)
B: Should be a `milestone` object instead of `milestone_id`. Same for `deal` and same for `.info`.

2019-05-29 16:36 UTC, psrpinto requested changes

2019-05-29 16:36 UTC, regularjack commented on src/changes-backwards-compatible.apib
> +- `tasks.list` and `tasks.info` now returns the milestone and deal objects.
```suggestion
- `tasks.list` and `tasks.info` now return the milestone and deal objects.
```

2019-05-29 16:36 UTC, regularjack commented on apiary.apib
> +        + deal_id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string, optional)
B: These changes are not from this PR, right? Same for the whitespace changes.

2019-05-31 07:43 UTC, mikeverf approved these changes

2019-06-03 09:40 UTC, psrpinto approved these changes
I think it would have been better to figure out why the unwanted changes were here and act accordingly, instead of removing them through extra commits. Also, the whitespace changes are still there.

2019-06-03 14:40 UTC, JorenSaey approved these changes

2019-06-04 08:40 UTC, jenssegers approved these changes

2019-06-04 22:10 UTC, stivni commented
> I think it would have been better to figure out why the unwanted changes were here and act accordingly, instead of removing them through extra commits.

Indeed, because if these commits get to master, those lines will be removed if they are in master...

2019-06-04 22:12 UTC, stivni reviewed
I wonder if we need to put this both as a top level property...
Have you considered other options, like a "links" section?
Not sure if that makes more sense here, but want to consider it for a second...

2019-06-05 11:02 UTC, r1dotl commented
This is already a mess, so i will close this one and open a new one clean.

2019-06-05 11:06 UTC, closed without merging

2019-06-05 11:06 UTC, r1dotl commented
Creating a new one more clean.