IN-901 Add ubl/e-fff format to invoices download
teamleadercrm/api pull request #486
Opened 2020-01-22 12:51 UTC by luisabritotl

2020-01-22 14:00 UTC, lowiebenoot submitted a review, later dismissed

2020-01-22 15:56 UTC, dietrichm requested changes

2020-01-22 15:56 UTC, dietrichm commented on src/05-invoicing/invoices.apib
> +                + ubl/e-fff
B: this does not seem to render correctly in the generated documentation.
```suggestion
                + `ubl/e-fff`
```

2020-01-22 18:50 UTC, lowiebenoot approved these changes

2020-01-23 08:10 UTC, sanderbrugge approved these changes

2020-01-23 08:28 UTC, dietrichm approved these changes
🙌

2020-01-23 08:29 UTC, dietrichm commented
✅ Checked

2020-01-23 09:12 UTC, EOSullivanBerlin approved these changes

2020-01-30 09:47 UTC, merged