In-2472 Add lost_reason to deals.list
teamleadercrm/api pull request #494
Opened 2020-02-04 10:16 UTC by luisaterrabrito

2020-02-04 10:53 UTC, sanderbrugge submitted a review, later dismissed

2020-02-04 13:38 UTC, EOSullivanBerlin submitted a review, later dismissed

2020-02-04 13:42 UTC, steftrenson submitted a review, later dismissed

2020-02-04 16:26 UTC, tiagobastos commented on apiary.apib
> +- We added lost_reason to the response of to `deals.list`.
Other fields in the `Latest` section have backtick around them. 
For consistency `lost_reason` should have too.

2020-02-04 16:26 UTC, tiagobastos commented on src/changes-backwards-compatible.apib
> +- We added lost_reason to the response of to `deals.list`.
Here too.

2020-02-05 09:11 UTC, sanderbrugge submitted a review, later dismissed

2020-02-05 09:15 UTC, tiagobastos submitted a review, later dismissed

2020-02-05 10:00 UTC, EOSullivanBerlin submitted a review, later dismissed

2020-02-05 12:44 UTC, dietrichm requested changes

2020-02-05 12:44 UTC, dietrichm commented on src/03-deals/deals.apib
> +                        + type: lost_reason (string)
B: types are camel cased, so this should be `lostReason`.

IIRC this is also a requirement to have the lost reasons sideloaded.

2020-02-05 12:44 UTC, dietrichm commented on src/03-deals/deals.apib
> +                + lost_reason (object)
PP: place the `lost_reason` _before_ meta data properties (`created_at`, `updated_at` and `web_url`).

2020-02-05 12:44 UTC, dietrichm commented on src/changes-backwards-compatible.apib
> +- We added `lost_reason` to the response of to `deals.list`.
PP:
```suggestion
- We added `lost_reason` to the response of `deals.list`. This is composed of a `lostReason` object along with a more elaborate `remark`.
```

2020-02-05 13:10 UTC, sanderbrugge submitted a review, later dismissed

2020-02-05 13:54 UTC, tiagobastos submitted a review, later dismissed

2020-02-05 14:34 UTC, dietrichm submitted a review, later dismissed

2020-02-06 13:18 UTC, EOSullivanBerlin submitted a review, later dismissed

2020-02-25 09:11 UTC, lowiebenoot submitted a review, later dismissed

2020-02-25 10:03 UTC, tiagobastos submitted a review, later dismissed

2020-02-25 13:35 UTC, dietrichm commented on src/03-deals/deals.apib
> +                    + remark: `Too expensive` (string, nullable)
Q: can it happen that `lost_reason` is provided, but both or either reason or remark are `null`?

2020-02-25 13:49 UTC, dietrichm commented on src/03-deals/deals.apib
> +                    + remark: `Too expensive` (string, nullable)
Explained by @luisaterrabrito IRL; if the reason is unknown, there is no `lostReason` set.

2020-02-25 13:49 UTC, dietrichm submitted a review, later dismissed

2020-02-25 14:53 UTC, sanderbrugge submitted a review, later dismissed

2020-02-25 15:36 UTC, EOSullivanBerlin submitted a review, later dismissed

2020-02-28 08:39 UTC, EOSullivanBerlin approved these changes

2020-02-28 08:45 UTC, sanderbrugge approved these changes

2020-02-28 09:08 UTC, lowiebenoot approved these changes

2020-02-28 09:38 UTC, tiagobastos approved these changes

2020-02-28 09:39 UTC, merged