In-2492 Add lost_reason to deals.info
teamleadercrm/api pull request #495
Opened 2020-02-04 10:20 UTC by luisaterrabrito

2020-02-04 10:53 UTC, sanderbrugge submitted a review, later dismissed

2020-02-04 13:31 UTC, EOSullivanBerlin submitted a review, later dismissed

2020-02-04 13:42 UTC, steftrenson submitted a review, later dismissed

2020-02-04 16:26 UTC, tiagobastos submitted a review, later dismissed

2020-02-05 12:52 UTC, dietrichm requested changes

2020-02-05 12:52 UTC, dietrichm commented on src/03-deals/deals.apib
> +                    + type: lost_reason (string)
B: types are camel cased, so this should be `lostReason`.

IIRC this is also a requirement to have the lost reasons sideloaded.

2020-02-05 12:52 UTC, dietrichm commented on src/03-deals/deals.apib
> +            + lost_reason (object)
PP: place the `lost_reason` _before_ meta data properties (`created_at`, `updated_at` and `web_url`).

2020-02-05 12:52 UTC, dietrichm commented on src/changes-backwards-compatible.apib
> +- We added `lost_reason` to the response of `deals.info`.
PP: have #494 as the base branch and add `deals.info` to the addition added there.

2020-02-05 13:08 UTC, sanderbrugge commented on apiary.apib
> +                    + type: lost_reason (string)
Q: Shouldn't this be camelcased too?

2020-02-05 13:56 UTC, tiagobastos submitted a review, later dismissed

2020-02-05 14:16 UTC, sanderbrugge submitted a review, later dismissed

2020-02-05 14:37 UTC, dietrichm submitted a review, later dismissed

2020-02-06 13:18 UTC, EOSullivanBerlin submitted a review, later dismissed

2020-02-25 09:10 UTC, lowiebenoot approved these changes

2020-02-25 10:04 UTC, tiagobastos approved these changes

2020-02-25 13:36 UTC, dietrichm commented on src/03-deals/deals.apib
> +                + remark: `Too expensive` (string, nullable)
Q: can it happen that `lost_reason` is provided, but both or either reason or remark are `null`?

2020-02-25 13:49 UTC, dietrichm commented on src/03-deals/deals.apib
> +                + remark: `Too expensive` (string, nullable)
Explained by @luisaterrabrito IRL; if the reason is unknown, there is no `lostReason` set.

2020-02-25 13:50 UTC, dietrichm approved these changes

2020-02-25 14:53 UTC, sanderbrugge approved these changes

2020-02-25 15:35 UTC, EOSullivanBerlin approved these changes

2020-02-28 08:34 UTC, merged