Add ids filter to lostReasons.list
teamleadercrm/api pull request #511
Opened 2020-03-20 13:53 UTC by lowiebenoot

Title speaks for itself.

2020-03-20 13:58 UTC, EOSullivanBerlin submitted a review, later dismissed

2020-03-20 14:17 UTC, sanderbrugge submitted a review, later dismissed

2020-03-23 10:35 UTC, luisaterrabrito submitted a review, later dismissed

2020-03-23 11:07 UTC, dietrichm requested changes

2020-03-23 11:07 UTC, dietrichm commented on src/changes-backwards-compatible.apib
> +- we added an `ids` filter to `lostReasons.list`.
B: typo?
```suggestion
- We added an `ids` filter to `lostReasons.list`.
```

2020-03-23 13:25 UTC, dietrichm submitted a review, later dismissed

2020-03-23 13:54 UTC, luisaterrabrito submitted a review, later dismissed

2020-03-23 14:32 UTC, sanderbrugge approved these changes

2020-03-23 15:49 UTC, luisaterrabrito approved these changes

2020-03-23 17:04 UTC, dietrichm approved these changes

2020-03-24 08:52 UTC, EOSullivanBerlin approved these changes

2020-03-24 09:27 UTC, steftrenson approved these changes

2020-03-25 12:33 UTC, merged