PRO-3623 - Add purchase_order_number to projects
teamleadercrm/api pull request #526
Opened 2020-05-11 13:05 UTC by Pegasuz

This PR adds the "purchase_order_number" to the projects.info, projects.create and projects.update endpoints.

Link to JIRA: https://teamleader.atlassian.net/browse/PRO-3623

2020-05-11 13:18 UTC, joaoinacio commented on apiary.apib
> +            + purchase_order_number: `000023` (string)
It should be `nullable`, IIRC?

2020-05-11 16:16 UTC, adognameddog requested changes
Purchase order number should be nullable, like @joaoinacio mentioned. Otherwise looking good!

2020-05-12 06:26 UTC, ketlane submitted a review, later dismissed

2020-05-12 12:01 UTC, ArnaudWeyts submitted a review, later dismissed

2020-05-12 15:05 UTC, ketlane commented on apiary.apib
> +#### April 2020
Not sure we should add the month grouping in this PR, but I'm not sure we shouldn't either. Maybe there are other opinions about it?

2020-05-12 21:06 UTC, adognameddog commented on apiary.apib
> +#### April 2020
If someone adds new documentation in June, then that person should add a new header and place everything from latest in there.

2020-05-12 21:06 UTC, adognameddog submitted a review, later dismissed

2020-05-13 08:10 UTC, mikeverf submitted a review, later dismissed

2020-05-18 10:49 UTC, joaoinacio submitted a review, later dismissed

2020-05-20 08:33 UTC, adognameddog approved these changes

2020-05-20 08:34 UTC, mikeverf approved these changes

2020-05-20 08:34 UTC, ArnaudWeyts approved these changes

2020-05-20 08:40 UTC, merged