Document that booked invoices can not be updated
teamleadercrm/api pull request #599
Opened 2021-08-02 11:24 UTC by steftrenson

We've got feedback that it wasn't clear that booked invoices can not be updated. Let's improve the documentation for the endpoint.

2021-08-02 11:37 UTC, lorgan3 submitted a review, later dismissed

2021-08-02 13:51 UTC, MathiasDL requested changes

2021-08-02 13:51 UTC, MathiasDL commented on apiary.apib
> +Update a draft invoice. Booked invoices can not be updated.
```suggestion
Update a draft invoice. Booked invoices cannot be updated.
```

2021-08-02 13:51 UTC, MathiasDL commented on src/05-invoicing/invoices.apib
> +Update a draft invoice. Booked invoices can not be updated.
```suggestion
Update a draft invoice. Booked invoices cannot be updated.
```

2021-08-02 13:52 UTC, MathiasDL commented
As seen all over the codebase, "can not" doesn't exist in English, it is "cannot"

2021-08-02 14:06 UTC, steftrenson commented
I can not believe that

2021-08-02 14:07 UTC, MathiasDL approved these changes

2021-08-02 14:09 UTC, lorgan3 approved these changes

2021-08-05 12:03 UTC, mrtus approved these changes

2021-08-06 14:07 UTC, merged