Invoices | Add late fees to invoices.list & invoices.info
teamleadercrm/api pull request #736
Opened 2023-09-25 09:03 UTC by tiagobastos

2023-09-25 09:04 UTC, joaoinacio approved these changes, later dismissed

2023-09-25 09:53 UTC, lorgan3 approved these changes, later dismissed

2023-09-25 12:53 UTC, Jdww submitted a review, later dismissed

2023-10-11 08:38 UTC, BrechtBonte requested changes, later dismissed

2023-10-11 08:38 UTC, BrechtBonte commented on apiary.apib
> +Get details for a single invoice.xcvxcvxcvxcvxcvxcv iensrionerst
B: I think this one was not intended

2023-10-11 15:10 UTC, BrechtBonte approved these changes, later dismissed

2023-10-11 16:06 UTC, Jdww approved these changes, later dismissed

2023-10-12 07:38 UTC, lorgan3 approved these changes, later dismissed

2023-10-12 16:11 UTC, joaoinacio approved these changes

2023-10-12 16:11 UTC, joaoinacio commented
✅

2023-10-12 16:23 UTC, Jdww approved these changes

2023-10-12 16:28 UTC, merged