ATL-117 Calls and Call outcome
teamleadercrm/api pull request #743
Opened 2023-10-13 14:41 UTC by Jdww

2023-10-13 14:44 UTC, mrtus commented on apiary.apib
> +            + employee_id: `b570e8c4-6c62-0f7a-a55b-6f330a127410` (string, optional) - Filter calls by user
This must be user id
```suggestion
            + user_id: `b570e8c4-6c62-0f7a-a55b-6f330a127410` (string, optional) - Filter calls by user
```

2023-10-13 14:49 UTC, Jdww commented on apiary.apib
> +            + employee_id: `b570e8c4-6c62-0f7a-a55b-6f330a127410` (string, optional) - Filter calls by user
Removed

2023-10-13 14:50 UTC, mrtus approved these changes

2023-10-16 09:25 UTC, joaoinacio approved these changes

2023-10-16 10:28 UTC, tiagobastos requested changes
nitpick: Sort the `.list` & `.info` alphabetically so it's easier to identify which fields are missing/added when comparing both.

2023-10-16 10:28 UTC, tiagobastos commented on apiary.apib
> +                + id: `13` (number)
B: We don't have integer identifiers. Same for info.

2023-10-16 10:28 UTC, tiagobastos commented on apiary.apib
> +                + status: `open` (string)
Shouldn't this be an enum of available status? 
Same for info.

2023-10-16 12:08 UTC, tiagobastos approved these changes

2023-10-30 17:07 UTC, tiagobastos commented
✔️ Manually checked

2023-10-30 17:07 UTC, merged