Add ledger(product_category) to invoices.info
teamleadercrm/api pull request #87
Opened 2018-03-09 09:49 UTC by luisabritotl

2018-03-09 14:19 UTC, lowiebenoot commented
It doesn't make sense to me that we use `product_category_id` directly.

It would make more sense to me if it was like this:

```
product_category (object, nullable)
    type: `product_category` (string)
    id: `e2314517-3cab-4aa9-8471-450e73449041` 
    ledger_account_number: 70100 (number, nullable)
```

Not sure if the `ledger_account_number` should be inside the product category object though.

@jenssegers?

2018-03-13 08:23 UTC, jenssegers commented on src/05-invoicing/invoices.apib
> +                            + product_category_id: `e2314517-3cab-4aa9-8471-450e73449041` (string, nullable)
This should be an `product_category` object.

 :ok: by @luisabritotl on 13/03/2018 09:10:47

2018-03-13 08:23 UTC, jenssegers requested changes

2018-03-13 08:23 UTC, jenssegers commented on src/05-invoicing/invoices.apib
> +                            + ledger_account_number: 70100 (number, nullable)
This can go.

2018-03-13 09:12 UTC, lowiebenoot approved these changes

2018-03-13 09:40 UTC, jenssegers commented on apiary.apib
> +                                + type: `product_category` (string)
`type` values are camelCased, so should be `productCategory` here.

2018-03-13 09:41 UTC, jenssegers requested changes

2018-03-13 09:41 UTC, jenssegers commented on apiary.apib
> +                                + type: `product_category` (string)
`type` values are camelCased, so should be `productCategory` here.

2018-03-13 09:43 UTC, jenssegers approved these changes

2018-03-13 12:54 UTC, jdrieghe approved these changes

2018-03-13 13:43 UTC, lowiebenoot approved these changes

2018-03-15 08:15 UTC, steftrenson approved these changes

2018-03-15 11:35 UTC, merged